
---
- name: ensure python-software-properties is installed
  apt: pkg=python-software-properties state=installed

- name: add rabbitmq official apt repository
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: install rabbitmq
  apt: pkg=rabbitmq-server={{rabbitmq_version}} state=installed force=yes
